export interface Project {
  slug: string;
  title: string;
  subtitle: string;
  img: string;
  category: string;
  location: string;
  year: string;
  description: string;
  gallery: string[];
}

export const projects: Project[] = [
  {
    slug: "canyon-cool",
    title: "Canyon Cool",
    subtitle: "A contemporary mountain retreat blending modern lines with natural warmth",
    img: "/images/380A5980-Edit-scaled.jpg",
    category: "New Construction",
    location: "Park City, Utah",
    year: "2024",
    description: "Nestled in the heart of a Park City canyon, this residence embraces the landscape with floor-to-ceiling windows and a material palette drawn from the surrounding terrain. Clean architectural lines are softened by warm wood tones, textured stone, and curated furnishings that invite you to settle in and stay.",
    gallery: ["/images/380A5980-Edit-scaled.jpg", "/images/380A5871-Edit-scaled.jpg", "/images/380A6184-Edit-scaled.jpg"],
  },
  {
    slug: "laurel-creek",
    title: "Laurel Creek",
    subtitle: "Timeless elegance meets mountain living",
    img: "/images/380A6353-Edit-scaled.jpg",
    category: "New Construction",
    location: "Park City, Utah",
    year: "2024",
    description: "Laurel Creek is a testament to understated luxury. Every room flows with intention, marrying refined finishes with the rugged beauty of the Wasatch Mountains. Custom millwork, handpicked stone, and a muted earth-tone palette create a sanctuary that feels both elevated and deeply personal.",
    gallery: ["/images/380A6353-Edit-scaled.jpg", "/images/380A6320-Edit-scaled.jpg", "/images/380A6516-Edit-scaled.jpg"],
  },
  {
    slug: "fifth-avenue-ranch",
    title: "Fifth Avenue Ranch",
    subtitle: "Where ranch tradition meets refined sophistication",
    img: "/images/380A0051-Edit-scaled.jpg",
    category: "New Construction",
    location: "Kamas, Utah",
    year: "2023",
    description: "This expansive ranch property brings the spirit of the American West into a beautifully designed home. Rich leathers, reclaimed timbers, and bespoke ironwork honor the land's heritage while delivering every modern comfort. The result is a home that feels rooted and timeless.",
    gallery: ["/images/380A0051-Edit-scaled.jpg"],
  },
  {
    slug: "the-bridge-house",
    title: "The Bridge House",
    subtitle: "A dramatic transformation of a 1990s mountain home",
    img: "/images/380A0265-Edit-scaled.jpg",
    category: "Remodel",
    location: "Park City, Utah",
    year: "2023",
    description: "The Bridge House underwent a complete reimagining — from dated mountain cabin to a striking contemporary residence. Structural walls were opened, light was invited in, and a fresh material vocabulary of white oak, honed marble, and blackened steel gave the home a new identity.",
    gallery: ["/images/380A0265-Edit-scaled.jpg", "/images/380A0307-Edit-scaled.jpg"],
  },
  {
    slug: "into-the-woods",
    title: "Into The Woods",
    subtitle: "A secluded mountain hideaway wrapped in nature",
    img: "/images/mountiain-home-in-park-city-utah.jpg",
    category: "New Construction",
    location: "Park City, Utah",
    year: "2023",
    description: "Surrounded by towering pines, this home is designed to disappear into its setting while delivering extraordinary interior spaces. Natural materials and organic textures blur the boundary between indoors and out, creating a retreat that feels both wild and deeply refined.",
    gallery: ["/images/mountiain-home-in-park-city-utah.jpg"],
  },
  {
    slug: "speak-easy-play-hard",
    title: "Speak Easy, Play Hard",
    subtitle: "A lower level designed for entertaining",
    img: "/images/380A0404-Edit-scaled.jpg",
    category: "Interior Furnishings",
    location: "Park City, Utah",
    year: "2023",
    description: "This project transformed an underutilized lower level into an unforgettable entertainment space. A custom bar, plush seating, and moody lighting set the scene for evenings that range from intimate cocktail hours to lively gatherings.",
    gallery: ["/images/380A0404-Edit-scaled.jpg", "/images/380A0422-Edit-scaled.jpg"],
  },
  {
    slug: "sapphire-ridge",
    title: "Sapphire Ridge",
    subtitle: "Panoramic views meet polished interiors",
    img: "/images/380A6320-Edit-scaled.jpg",
    category: "New Construction",
    location: "Park City, Utah",
    year: "2022",
    description: "Perched high above the valley, Sapphire Ridge commands sweeping views from every room. The design celebrates this vantage point with expansive glass, a restrained palette, and furnishings scaled to the home's generous proportions.",
    gallery: ["/images/380A6320-Edit-scaled.jpg"],
  },
  {
    slug: "modern-meadow-remodel",
    title: "Modern Meadow Remodel",
    subtitle: "Breathing new life into a mid-century floor plan",
    img: "/images/380A0422-Edit-scaled.jpg",
    category: "Remodel",
    location: "Park City, Utah",
    year: "2022",
    description: "This comprehensive remodel honored the home's original bones while bringing every surface into the present. Walls came down, ceilings went up, and a fresh palette of warm whites, cerused oak, and bronze hardware created a home that feels effortlessly modern.",
    gallery: ["/images/380A0422-Edit-scaled.jpg"],
  },
  {
    slug: "fresh-take-on-french",
    title: "Fresh Take On French",
    subtitle: "French provincial charm with a contemporary twist",
    img: "/images/380A4159-HDR-Edit-scaled.jpg",
    category: "Interior Furnishings",
    location: "Salt Lake City, Utah",
    year: "2022",
    description: "Classic French design principles — symmetry, proportion, refined ornamentation — reinterpreted through a modern lens. Soft pastels, gilded accents, and sculptural furniture create rooms that feel both timeless and freshly curated.",
    gallery: ["/images/380A4159-HDR-Edit-scaled.jpg", "/images/380A4272-Edit-scaled.jpg", "/images/380A4513-Edit-scaled.jpg"],
  },
  {
    slug: "the-court-house",
    title: "The Court House",
    subtitle: "An indoor sports court surrounded by style",
    img: "/images/Court-House-1.jpg",
    category: "New Construction",
    location: "Park City, Utah",
    year: "2022",
    description: "The Court House proves that functional spaces can be beautiful. Centered around a full-size indoor sport court, the surrounding living areas deliver the same elevated design standard — proving that play and sophistication coexist beautifully.",
    gallery: ["/images/Court-House-1.jpg"],
  },
  {
    slug: "summit-4",
    title: "Summit 4",
    subtitle: "Ski-in luxury at its finest",
    img: "/images/380A0924-Edit-scaled.jpg",
    category: "New Construction",
    location: "Park City, Utah",
    year: "2021",
    description: "Steps from the slopes, Summit 4 is a ski-in residence designed for families who live and breathe the mountain lifestyle. Durable yet luxurious materials withstand daily use while maintaining an atmosphere of refined comfort.",
    gallery: ["/images/380A0924-Edit-scaled.jpg"],
  },
  {
    slug: "the-lake-house",
    title: "The Lake House",
    subtitle: "Lakefront living with curated calm",
    img: "/images/2023-01-15-V2-Bond-Eden-Lakehouse-3964-nicole-gerulat.jpg",
    category: "New Construction",
    location: "Eden, Utah",
    year: "2021",
    description: "Overlooking a pristine mountain lake, this home channels the serenity of its setting into every design decision. Soft linens, weathered wood, and a water-inspired palette create a retreat that feels like a permanent exhale.",
    gallery: ["/images/2023-01-15-V2-Bond-Eden-Lakehouse-3964-nicole-gerulat.jpg"],
  },
  {
    slug: "desert-spanish-retreat",
    title: "Desert Spanish Retreat",
    subtitle: "Old-world warmth in a desert setting",
    img: "/images/Desert-Spanish-Retreat-Living.jpg",
    category: "New Construction",
    location: "St. George, Utah",
    year: "2021",
    description: "Inspired by the haciendas of the American Southwest, this home combines terracotta warmth, hand-troweled plaster, and arched doorways with modern furnishings. The result is a home that honors tradition while living firmly in the present.",
    gallery: ["/images/Desert-Spanish-Retreat-Living.jpg", "/images/Desert-Spanish-Retreat-Kitchen.jpg"],
  },
  {
    slug: "a-fresh-perspective",
    title: "A Fresh Perspective",
    subtitle: "A full home refresh with maximum impact",
    img: "/images/380A4513-Edit-scaled.jpg",
    category: "Interior Furnishings",
    location: "Park City, Utah",
    year: "2020",
    description: "Sometimes a home just needs fresh eyes. This project replaced every furnishing, textile, and accessory to give a well-built home the interior it deserved — layered, cohesive, and full of personality.",
    gallery: ["/images/380A4513-Edit-scaled.jpg"],
  },
  {
    slug: "good-things-come-in-small-packages",
    title: "Good Things Come In Small Packages",
    subtitle: "Big design in a compact footprint",
    img: "/images/380A0654-Edit-scaled.jpg",
    category: "Remodel",
    location: "Park City, Utah",
    year: "2020",
    description: "This smaller mountain home proves that luxury is not about square footage. Every inch was designed with intention, using built-ins, thoughtful lighting, and a refined material palette to create spaces that feel generous and considered.",
    gallery: ["/images/380A0654-Edit-scaled.jpg"],
  },
  {
    slug: "mountain-state-of-mind",
    title: "Mountain State Of Mind",
    subtitle: "Modern mountain living at elevation",
    img: "/images/380A6650-Edit-scaled.jpg",
    category: "New Construction",
    location: "Park City, Utah",
    year: "2020",
    description: "Mountain State of Mind captures the essence of elevated mountain living. With a focus on natural materials and sweeping sightlines, each room frames the landscape like a work of art while delivering the warmth and comfort of home.",
    gallery: ["/images/380A6650-Edit-scaled.jpg"],
  },
  {
    slug: "fly-right-in",
    title: "Fly Right In",
    subtitle: "Hangar-adjacent living with aviation flair",
    img: "/images/380A6740-Edit-Recovered-scaled.jpg",
    category: "New Construction",
    location: "Heber City, Utah",
    year: "2019",
    description: "Built alongside a private airstrip, Fly Right In takes design cues from aviation — streamlined forms, metallic accents, and expansive views of the runway. It is a home as adventurous as its owners.",
    gallery: ["/images/380A6740-Edit-Recovered-scaled.jpg"],
  },
  {
    slug: "the-bond-studio",
    title: "The Bond Studio",
    subtitle: "Our creative home base in Park City",
    img: "/images/2023-02-08-Bond-Studio4901-nicole-gerulat-1.jpg",
    category: "Commercial",
    location: "Park City, Utah",
    year: "2023",
    description: "The Bond Studio is where our team gathers, creates, and brings visions to life. Designed as a living portfolio of our work, the studio balances productivity with beauty — a space that inspires the work that happens within it.",
    gallery: ["/images/2023-02-08-Bond-Studio4901-nicole-gerulat-1.jpg", "/images/Bond-Design-Company-Philosophy.jpg"],
  },
];
